Wasn't compiling:  UnitTests\AppReminderRuleTests.cs(24,68): error CS1061: 'ShortCodeAttribute' does not contain a definition for 'ShortCodeTemplatePrefName' and no accessible extension method 'ShortCodeTemplatePrefName' accepting a first argument of type 'ShortCodeAttribute' could be found (are you missing a using directive or an assembly reference?) [C:\Development\OPEN DENTAL SUBVERSION\head\UnitTests\UnitTests.csproj] - Just a unit test so commented it out for now.